### ISSUE TITLE
Please provided Maven Project for same

### ISSUE THREAD

**Issue by pashtika** [adrianbk/swagger-springmvc-demo#17]

**Comment by adrianbk** [comment]
@pashtika maintaining both a Gradle and a Maven version of this is impractical. Gradle, as a build and automation tool is far superior to Maven and hence we will be sticking with Gradle only.

 Some examples specific to this project: 

__Multiple test configurations within the same project__
![image](https://cloud.githubusercontent.com/assets/1910629/6090460/55c2fdfe-aece-11e4-8c0d-240057a61c65.png)
  
__Simple multi-module configuration__
![image](https://cloud.githubusercontent.com/assets/1910629/6090472/ed3e071e-aece-11e4-967b-77c38fc8ebca.png)

**Comment by pashtika** [comment]
Thanks for this. In-fact code provided is huge and I'm not able to understand it. I'm initially looking for simple Spring MVC Swagger which helps me to understand the concepts. Could you please guide me?
