### ISSUE TITLE
Newer version of swagger-spring-mvc-ui?

### ISSUE THREAD

**Issue by vivin** [adrianbk/swagger-springmvc-demo#20]
The current version of `org.ajar:swagger-spring-mvc-ui` is `0.4`, which uses Swagger-UI version 2.0.17. I'm running into an issue that seems to be similar to [this](https://github.com/swagger-api/swagger-ui/issues/467) issue in the Swagger-UI project. A fix is present in Swagger-UI version 2.0.19. I was wondering if there were plans to update `swagger-spring-mvc-ui` to use the new version of Swagger-UI?

If no one objects, I can submit a pull request that uses the latest version of Swagger UI.

**Comment by vivin** [comment]
Well, I'm pretty stupid. I should have read the docs more thoroughly. I was going off what I saw in the artifact itself! I see that you can control the version using `swaggerUiVersion`!

**Comment by adrianbk** [comment]
@vivin what exactly is the issue you are having? It may not be swagger-ui related. Have you read the section on [endpoints](https://github.com/springfox/springfox#api-documentation-endpoints)

I'm not keen on upgrading the webjar to a newer version of swagger-ui, I've tried this in the past and it hasn't worked out so well. The  reason is that as it stands this webjar needs to be something we know works with swagger-springmvc (swagger spec 1.2). Technically the latest swagger-ui version works with the swagger spec versions 1.2 and 2.0 but the last time I tried it the latest swagger-ui version was not 100% backwards compatible with swagger spec 1.2.

We are working on supporting swagger spec 2.0 and once that becomes available there will be a web jar with the latest swagger-ui.

**Comment by vivin** [comment]
I will take a look at the end points. It is entirely possible that my configuration is wrong. I wasn't aware that that swagger-ui was linked to the version of swagger the swagger spec in swagger-springmvc. It completely makes sense then why you'd be reluctant to upgrade. Thanks for your help, and thanks for all the good work you guys have done!

**Comment by dilipkrish** [comment]
@vivin just to clarify, swagger-springmvc has no dependency on swagger-ui.  It only has a dependence on the spec. 

The demo app exists only to showcase the features. So consequently we only upgrade the swagger-ui in lockstep with the version of the spec that is currently supported by it.

**Comment by vivin** [comment]
Ah, yes that's what I meant to write. It makes a lot of sense why you would do this.
